name: Goodtimes
favicon: null
layout_spectrum: 0.8870572433806956
typography_spectrum: 0.36447776202112436
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#322225'
    - '#53575a'
    - '#e8cfd2'
    - '#9696a3'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
