name: Goodtimes
favicon: null
layout_spectrum: 0.24168
typography_spectrum: 0.74268
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3e4a58'
    - '#252932'
    - '#70874f'
    - '#aa9d71'
    - '#ecebe6'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
